spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tinderzoo_dev
    username: tinderzoo_dev_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  resources:
      add-mappings: true
  #batch:
   # job:
   #   enabled: false
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1149004038908516
            client-secret: 629e01193ced516125c77580f3b0d2c9
            scope:
              - email
              - public_profile
