server:
    port=8080
spring:
  datasource:
    url: jdbc:mysql://database-1.ccx7e8ktpswy.eu-central-1.rds.amazonaws.com:3306/tinderzoo_dev
    username: root
    password: 11223344
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect=org.hibernate.dialect.MySQL8Dialect

    database: mysql
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1149004038908516
            client-secret: 629e01193ced516125c77580f3b0d2c9
            scope:
              - email
              - public_profile
